### ISSUE TITLE
Landing page pictures

### ISSUE THREAD

**Issue by hurtonypeter** [hurtonypeter/alumni-vienna#15]
We will need some big pictures for the home page:

* 2440x1578px for the first full-screen image, top of the page
* 2101x1578px for the 3number1percentage section
* 125x100px for the testimonial logos

**Comment by harlecin** [comment]
Can you try to use the picture called WU3-2.jpg that I put in the zip folder for the very top picture?

I need to check if we can get that in higher resolutions

**Comment by hurtonypeter** [comment]
That is way too small :(

**Comment by harlecin** [comment]
I just send you one on fb that has the correct dimension, but it is about 5mb

**Comment by harlecin** [comment]
I need to find one for the 3number1percentage section

**Comment by hurtonypeter** [comment]
I made the others hidden, so I close this for now. If we have good images for the others later, we can reopen.
