### ISSUE TITLE
Icons for the "What do we offer?" section

### ISSUE THREAD

**Issue by hurtonypeter** [hurtonypeter/alumni-vienna#16]
We will need 4 icons for the

* casual meetups
* job board
* access to alumni network
* talks by industry experts

Icons are available from the fontawesome library. Gallery can be found here: http://fontawesome.io/icons/

**Comment by harlecin** [comment]
- Casual meetups -> keep as is
- job board -> briefcase
- access to alumni network: graduation-cap
- talks by industry experts -> comment
